# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Runtime image for a prebuilt linux/amd64 binary:
#   cargo zigbuild --release --target x86_64-unknown-linux-gnu.2.28
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
COPY keycloak-registrar-interceptor /usr/local/bin/keycloak-registrar-interceptor
USER 1001
ENTRYPOINT ["/usr/local/bin/keycloak-registrar-interceptor"]
